### ISSUE TITLE
Use state bag Filter

### ISSUE THREAD

**Issue by JericoFX** [RPX-RedM/rpx-inventory#4]
Hi, awesome conversion!.
You can use the statebag Filter player:serverID
```lua
AddStateBagChangeHandler("job", "player:serverID", function(bagName, key, value) 
```
so you dont need this check
https://github.com/RPX-RedM/rpx-inventory/blob/0dc2cb10dc087b42a0b66decea77ba0a102cd952/modules/bridge/rpx/client.lua#L6
if you use ox lib you can do 

```lua
AddStateBagChangeHandler("job", ("player:%s"):format(cache.serverId), function(bagName, key, value) 
```

**Comment by Zer0Cool0** [comment]
@youngsinatra99 This can be closed. Fixed with PR #3
